### ISSUE TITLE
IS-IS allow multiple NET addresses per router

### ISSUE THREAD

**Issue by DanPartelly** [ipspace/netlab#2556]
We should allow multiple NET addresses per router, so devices can participate in more than one area at once. Some platforms also have a configurable number of maximum areas addresses a router can be part of. 

( Ex.  max-area-addresses on ios xe - defaults to 3. )

maybe from plugin ?

**Comment by ipspace** [comment]
IIRC, multiple NETs per router are used to merge/split level-1 areas, and that's definitely not something I'd like to have as a core functionality. It's definitely something that should be solved in a plugin.

Also, how many implementations support that?

**Comment by DanPartelly** [comment]
>multiple NETs per router are used to merge/split level-1 areas, and that's definitely not something I'd like to have as a core >functionality. It's definitely something that should be solved in a plugin.

Indeed. 

Another question, is this practically something which is useful to anything else then controlling area migrations ? Ive learned a lot about this protocol during the last month and labbed the crap out of it (all your labs, segment routing,  all ideas I posted on you isis labs github) , but I am still not  tuned to the practical relevance for some of those things. Leaving areas aside for a moment, are mesh groups really used in practice ? That one in particular looked to me as one of the fastest ways to go interstellar and blackhole your whole transit network should the wrong router fails.  

> Also, how many implementations support that?

No idea. All ios/xe/xr family does, but would need to check against the other usual suspects.

**Comment by ipspace** [comment]
> Another question, is this practically something which is useful to anything else then controlling area migrations?

Haven't found another use case yet.

> are mesh groups really used in practice?

Maybe at the customer that pushed Cisco to implement them? ;)

**Comment by DanPartelly** [comment]
Scratch this as another iffy idea  then. Not worth it.  A plugin would be trivial, if neeeds ever arises.
